# Generated by Django 2.2 on 2019-05-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
